### ISSUE TITLE
Array of array problem in validation

### ISSUE THREAD

**Issue by spamik** [pysimplesoap/pysimplesoap#102]
I have problem with system which want on input dict, which is located in two arrays. I have this variable in Python, which I passing as argument to soap function:

variables_key = [
    [
        {
            'IsKey': True,
            'Key': 'GUID',
            'Value': '2905a75f-414d-44d5-ba0c-c4307c92666f'
         }
    ]
]

In this attachment is WSDL regarding types used in this application. Argument is using type ArrayOfArrayOfKeyValuePair.
[wsdl.xml.txt](https://github.com/pysimplesoap/pysimplesoap/files/32039/wsdl.xml.txt)

When I run query with this argument, script fails with error TypeError: unhashable type: 'dict' in client.py:465. I've tried some debugging and I believe that there is some bug in validation function or in completing struct. Issue is that struct seems like that:
[{u'ArrayOfKeyValuePair': [{u'KeyValuePair': {u'IsKey': <type 'bool'>, u'Key': <type 'str'>, u'Value': <type 'str'>}}]}]

When validation function starts validating first array, it consider struct as dict (because struct is u'ArrayOfKeyValuePair': ...) and starts iterating list. So it takes first value of list (which is dict) and test if it's in struct. And condition dict in dict fails because dict can't be key of dict.

**Comment by mikelo** [comment]
forked repository with list arguments marshalling 
https://github.com/mikelo/pysimplesoap
does is solve the issue? are you using axis server?

**Comment by spamik** [comment]
Not working but different error - now it crashes in same place but with message unhashable type: list (previsously unhashable type: dict). Not using axis server, just simple script on my side (just one call to SOAP) and proprietary database with SOAP interface on the other side.

**Comment by laxmikantra** [comment]
I have similar problem even with its own testcase:

```
----------------------------------------
serviceMsisdn <class 'str'>
serviceName <class 'str'>
activations [{'items': {'properties': ({'name': <class 'str'>, 'value': <class 'str'>},), 'parameters': <class 'str'>, 'status': <class 'int'>, 'msisdn': <class 'str'>}}]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51652)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/laxmikant/work/penv/lib/python3.5/site-packages/pysimplesoap/server.py", line 460, in do_GET
    response = self.server.dispatcher.wsdl()
  File "/home/laxmikant/work/penv/lib/python3.5/site-packages/pysimplesoap/server.py", line 393, in wsdl
    parse_element("%s" % method, args and args.items())
  File "/home/laxmikant/work/penv/lib/python3.5/site-packages/pysimplesoap/server.py", line 374, in parse_element
    if v in TYPE_MAP.keys():
TypeError: unhashable type: 'list'
----------------------------------------```
