### ISSUE TITLE
pysimplesoap with a method that expects several parameters

### ISSUE THREAD

**Issue by boriscougar** [pysimplesoap/pysimplesoap#124]
Hi, I've been trying to use pysimplesoap with an WSDL, I don't know how to know if the WSDL is broken but I'm also not sure how to use pysimplesoap withouat a WSDL so I do the following:

```
from gluon.contrib.pysimplesoap.client import SoapClient
import logging
logging.getLogger().setLevel(logging.DEBUG)
import base64
encoded = "iusr_tcorp:T!go@2014"
encoded = base64.b64encode(encoded)
client = SoapClient(wsdl="https://server_address/meaweb/wsdl/MXINCIDENT.wsdl", trace = True, http_headers={'Authorization': 'Basic %s' % encoded})
```

So far everything seems right, the WSDL is parsed and so I can call the following:

`client.CreateMXINCIDENT(MXINCIDENTSet={})`

And the debug output shows this:

```
>>> client.CreateMXINCIDENT(MXINCIDENTSet = {})
INFO:gluon.contrib.pysimplesoap.client:POST https://server_url/meaweb/services/MXINCIDENT
DEBUG:gluon.contrib.pysimplesoap.client:SOAPAction: "urn:processDocument"
Content-length: 361
Content-type: text/xml; charset="UTF-8"
Authorization: Basic a9ycDTQ=
DEBUG:gluon.contrib.pysimplesoap.client:<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soap:Header/>
<soap:Body>
    <CreateMXINCIDENT xmlns="http://www.ibm.com/maximo">
    <MXINCIDENTSet/></CreateMXINCIDENT>
</soap:Body>
</soap:Envelope>
DEBUG:gluon.contrib.pysimplesoap.client:date: Mon, 15 Feb 2016 13:43:43 GMT
transfer-encoding: chunked
connection: close
content-type: text/xml; charset=UTF-8
content-language: en-US
DEBUG:gluon.contrib.pysimplesoap.client:<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><CreateMXINCIDENTResponse xmlns="http://www.ibm.com/maximo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" creationDateTime="2016-02-15T07:43:53-06:00" transLanguage="EN" baseLanguage="EN" messageID="1455543823754375735"></CreateMXINCIDENTResponse></soapenv:Body></soapenv:Envelope>
```

So far everything is ok, I know the expected XML from the SOAP API is the following:
```
<S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope">
   <S:Body>
      <CreateMXINCIDENT xmlns="http://www.ibm.com/maximo">
         <MXINCIDENTSet>
            <INCIDENT>
               <ASSETORGID>COL</ASSETORGID>
               <CINUM>57502</CINUM>
               <CLASS>INCIDENT</CLASS>
               <CLASSIFICATIONID>185</CLASSIFICATIONID>
               <DESCRIPTION>Solicitud</DESCRIPTION>
               <DESCRIPTION_LONGDESCRIPTION>fdsa</DESCRIPTION_LONGDESCRIPTION>
               <ORGID>COMCEL</ORGID>
               <OWNERGROUP>CC_CORP</OWNERGROUP>
               <REPORTEDBY>Cliente Operador</REPORTEDBY>
               <REPORTEDEMAIL>asdf@gmail.com</REPORTEDEMAIL>
               <REPORTEDPHONE>82489429824</REPORTEDPHONE>
               <REPORTEDPRIORITY>2</REPORTEDPRIORITY>
               <SITEID>ON</SITEID>
            </INCIDENT>
         </MXINCIDENTSet>
      </CreateMXINCIDENT>
   </S:Body>
</S:Envelope>
```

So if I try to pass something like the following, which I expect to have it working:

`client.CreateMXINCIDENT(MXINCIDENTSet=[{"INCIDENT":{"ASSETORGID":"COL", "CINUM":57502, "CLASS":"INCIDENT", "CLASSIFICATIONID":185, "DESCRIPTION":"SOLICITUD", "DESCRIPTION_LONGDESCRIPTION":"Hola Mundo", "ORGID":"COMCEL", "OWNERGROUP": "CC_CORP", "REPORTEDBY":"Cliente", "REPORTEDEMAIL":"hello@me.com", "REPORTEDPHONE":"503333333", "REPORTEDPRIORITY":2, "SITEID":"ON"}}])`

I receive the following exception:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/web2py/gluon/contrib/pysimplesoap/client.py", line 167, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "/var/www/web2py/gluon/contrib/pysimplesoap/client.py", line 319, in wsdl_call
    method, params = self.wsdl_call_get_params(method, input, *args, **kwargs)
  File "/var/www/web2py/gluon/contrib/pysimplesoap/client.py", line 354, in wsdl_call_get_params
    raise ValueError('Invalid Args Structure. Errors: %s' % errors)
ValueError: Invalid Args Structure. Errors: [u"Args keys not in parameter. parameter: {}, args: [{'INCIDENT': {'REPORTEDBY': 'Cliente', 'SITEID': 'ON', 'ASSETORGID': 'COL', 'REPORTEDPHONE': '503333333', 'REPORTEDPRIORITY': 2, 'DESCRIPTION': 'SOLICITUD', 'CLASSIFICATIONID': 185, 'OWNERGROUP': 'CC_CORP', 'DESCRIPTION_LONGDESCRIPTION': 'Hola Mundo', 'CINUM': 57502, 'ORGID': 'COL', 'CLASS': 'INCIDENT', 'REPORTEDEMAIL': 'hello@me.com'}}]"]
```

I'm actually out of clues of how to achieve using this service with pysimplesoap, I'm not sure if the WSDL is good or bad, but here it is: http://pastebin.com/e3basiJ8

**Comment by comartmit** [comment]
I am running into the same issue with a confidential WSDL I am using. Basically the wsdl contains an operation whose input requires a complexType. The complex type extends another complex type, which extends another complex type. The resulting service that comes out of `services = self._xml_tree_to_services(wsdl, cache, force_download)` (client.py line 836) only takes a single flat argument (confirmed by printing out the service dict) and blows up if I attempt to pass it the full nested argument. I will continue to investigate as this is high urgency for me, but wanted to post my current discovery up here for someone who might be more familiar with the package.
