### ISSUE TITLE
Problem to connect me with WCF/SVC service .NET

### ISSUE THREAD

**Issue by kapsule** [pysimplesoap/pysimplesoap#129]
Hello, I am trying to connect me to a SOAP service and I just do not work properly. I don't know if the service in question has a complex structure but I just do not work :( Making the call to the method "startsession" it shows me the following error.

    url = "http://server/PublisherService/PublisherService.svc?wsdl"
    client = SoapClient(wsdl=url)
    print client.help('startSession')
    parameters = {'userName': 'demo', 'password': 'demo', 'language': '1'}

    try:
        response = client.startSession(**parameters)
        print response
    except SoapFault as e:
        response = "ERROR {0}: {1}".format(e.faultcode, e.faultstring)
        print response

No handlers could be found for logger "pysimplesoap.simplexml"
Traceback (most recent call last):
  File "/home/dfernandez/Dropbox/Proyectos/CRM/Desarrollo/Repositorios/parkare/pkr_pythonscripting/ParkareApp/pyTiparq/pyMain.py", line 55, in <module>
    test3()
  File "/home/dfernandez/Dropbox/Proyectos/CRM/Desarrollo/Repositorios/parkare/pkr_pythonscripting/ParkareApp/pyTiparq/pyMain.py", line 45, in test3
    response = client.startSession(**parameters)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 181, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 346, in wsdl_call
    return self.wsdl_call_with_args(method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 370, in wsdl_call_with_args
    response = self.call(method, *params)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 262, in call
    jetty=self.__soap_server in ('jetty',))
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/simplexml.py", line 56, in __init__
    self.__document = xml.dom.minidom.parseString(text)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

I've tried with another service (http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL) and it works for me without any problems.

The service which I am trying to I connect is as follows:

https://hosting.parkaregroup.com/PublisherService/PublisherService.svc?wsdl

I hope that I can help.

Thanks,

**Comment by kapsule** [comment]
Hi, Already I've been able to fix it. Thanks.
