### ISSUE TITLE
BinaryTokenSignature expects response to be signed

### ISSUE THREAD

**Issue by adamkerz** [pysimplesoap/pysimplesoap#139]
I'm helping someone else who is trying to use PySimpleSoap to interact with an internal service, so I don't have that much info (no doco of the service beyond the WSDL, which I can't share). We are required to sign our request, but it appears that the response is NOT signed. `BinaryTokenSignature` expects it to be.

```
Traceback (most recent call last):
  File "sign_soap_request.py", line 103, in <module>
    main()
  File "sign_soap_request.py", line 100, in main
    create_client()
  File "sign_soap_request.py", line 87, in create_client
    response=client.DENPing()
  File "D:\development\NTCMPythonSoap\venv\lib\site-packages\pysimplesoap\client.py", line 181, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "D:\development\NTCMPythonSoap\venv\lib\site-packages\pysimplesoap\client.py", line 346, in wsdl_call
    return self.wsdl_call_with_args(method, args, kwargs)
  File "D:\development\NTCMPythonSoap\venv\lib\site-packages\pysimplesoap\client.py", line 370, in wsdl_call_with_args
    response = self.call(method, *params)
  File "D:\development\NTCMPythonSoap\venv\lib\site-packages\pysimplesoap\client.py", line 279, in call
    self.__headers, soap_uri)
  File "D:\development\NTCMPythonSoap\venv\lib\site-packages\pysimplesoap\wsse.py", line 126, in postprocess
    wsse = header("Security", ns=WSSE_URI)
  File "D:\development\NTCMPythonSoap\venv\lib\site-packages\pysimplesoap\simplexml.py", line 247, in __call__
    raise AttributeError("Tag not found: %s (%s)" % (tag, e))
AttributeError: Tag not found: Security (No elements found)
```

Now I could be wrong, but shouldn't it be up to the server and the client to decide whether that's required or not? In this instance, the server has decided that it is NOT required. And, on the client side, I should be able to specify whether I will accept this or not - eg. a `response_must_be_signed` argument to `BinaryTokenSignature`

Pull request to come.

**Comment by adamkerz** [comment]
I've seen at least two other people implement fixes for this same problem in their forks too, so probably a desirable fix.
