### ISSUE TITLE
TypeError: fixer() missing 1 required positional argument: 'check_hostname'

### ISSUE THREAD

**Issue by nschloe** [pysimplesoap/pysimplesoap#162]
From https://github.com/httplib2/httplib2/issues/102:

I'm getting a funny exception when using [Debian's reportbug](https://packages.debian.org/sid/reportbug) that traces back to pysimplesoap/httplib2:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reportbug/ui/gtk2_ui.py", line 1049, in sync_pre_operation
    http_proxy=http_proxy, archived=archived, source=source)
  File "/usr/lib/python3/dist-packages/reportbug/debbugs.py", line 1073, in get_reports
    bugs = debianbts.get_bugs(pkg_filter, package)
  File "/home/nschloe/.local/lib/python3.6/site-packages/debianbts/debianbts.py", line 410, in get_bugs
    reply = soap_client.call('get_bugs', method_el)
  File "/home/nschloe/.local/lib/python3.6/site-packages/pysimplesoap/client.py", line 256, in call
    self.xml_response = self.send(method, self.xml_request)
  File "/home/nschloe/.local/lib/python3.6/site-packages/pysimplesoap/client.py", line 318, in send
    location, http_method, body=xml, headers=headers)
  File "/home/nschloe/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1396, in request
    self.disable_ssl_certificate_validation)
  File "/home/nschloe/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 979, in __init__
    timeout=timeout, context=context)
TypeError: fixer() missing 1 required positional argument: 'check_hostname'
```
The exception is triggerd in https://github.com/pysimplesoap/pysimplesoap/blob/master/pysimplesoap/transport.py#L72.

[The documentation](https://docs.python.org/3/library/http.client.html) says

> The check_hostname parameter is also deprecated; the ssl.SSLContext.check_hostname attribute of 
context should be used instead.

**Comment by oldium** [comment]
I faced the same bug, the problem is fixed by applying #150.

**Comment by oldium** [comment]
Yes, it fixes the issue.

**Comment by id8216** [comment]
Please fix this issue. I had same problem with fixer() when I change python version from 3.5 to 3.6 in my project  
https://github.com/httplib2/httplib2/issues/126

**Comment by gabn88** [comment]
When does this get merged? It bites me every so often, which is annoying and unnecessary.
