### ISSUE TITLE
1.16.2 seems to be broken

### ISSUE THREAD

**Issue by venthur** [pysimplesoap/pysimplesoap#167]
Version 1.16.2 seems to be broken across python2 and -3 and while the previous version was not.
```
Traceback (most recent call last):
  File "/home/travis/build/venthur/python-debianbts/test/test_debianbts.py", line 152, in test_bug_log_message_unicode
    buglogs = bts.get_bug_log(773321)
  File "/home/travis/build/venthur/python-debianbts/debianbts/debianbts.py", line 316, in get_bug_log
    reply = _soap_client_call('get_bug_log', nr)
  File "/home/travis/build/venthur/python-debianbts/debianbts/debianbts.py", line 488, in _soap_client_call
    return getattr(soap_client, method_name)(soap_client, *soap_args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pysimplesoap/client.py", line 175, in <lambda>
    return lambda *args, **kwargs: self.call(attr, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pysimplesoap/client.py", line 213, in call
    for k, v in parameters:  # dict: tag=valor
TypeError: 'SoapClient' object is not iterable
```

https://travis-ci.org/venthur/python-debianbts/builds/393292840

**Comment by nmartensen** [comment]
According to git bisect the problem was introduced by #88. Reverting that change indeed fixes it and makes reportbug work as desired again.

However, the change was made for a reason... @gaetano-guerriero, could you please have a look?
