### ISSUE TITLE
Error occurs when soap request is too large

### ISSUE THREAD

**Issue by dotnetdan** [pysimplesoap/pysimplesoap#37]
The following error is occurring when sending large requests from the client to a service.  It definitely appears to be related to size because the repro is as follows:

```python
client = SoapClient(wsdl="https://server/myService")
client.Insert(largeList[1:100]) # succeeds
client.Insert(largeList[1:150]) # error occurs
```

The error is:
```
No handlers could be found for logger "pysimplesoap.simplexml"
Traceback (most recent call last):
  File "rate.py", line 76, in <module>
    insertResult = r.bulkInsert()
  File "rate.py", line 51, in bulkInsert
    insertResult = self.client.BulkInsertFrom(contracts=rates)
  File "C:\Users\dling\Envs\lib\site-packages\pysimplesoap\client.py", line 181, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "C:\Users\dling\Envs\lib\site-packages\pysimplesoap\client.py", line 346, in wsdl_call
    return self.wsdl_call_with_args(method, args, kwargs)
  File "C:\Users\dling\Envs\lib\site-packages\pysimplesoap\client.py", line 370, in wsdl_call_with_args
    response = self.call(method, *params)
  File "C:\Users\dling\Envs\lib\site-packages\pysimplesoap\client.py", line 262, in call
    jetty=self.__soap_server in ('jetty',))
  File "C:\Users\dling\Envs\lib\site-packages\pysimplesoap\simplexml.py", line 56, in __init__
    self.__document = xml.dom.minidom.parseString(text)
  File "C:\Python27\Lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\Lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\Lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

**Comment by dotnetdan** [comment]
I am investigating this now.

**Comment by dotnetdan** [comment]
False alarm, turned out to be an issue with my server
