### ISSUE TITLE
Non-deterministic results after processing SOAP-reply.

### ISSUE THREAD

**Issue by towr** [pysimplesoap/pysimplesoap#49]
I've spent most of Friday seeing if I could run/fix the test sets, and ran into some interesting issues. For example, in the *issues_test* set, *test_issue109* sometimes succeeds, and sometimes fails; even when I record the response from the server and just play it back (**vcrpy** ftw)

*test_issue109* tests multirefs, and some runs `response['doEnsembleURIQueryReturn']` is None, and other times it's the expected list of returnvalues.

I've also run into a non-determinism issue with the *sri_ec_test* set, the result of the first test sometimes contains lists, and sometimes not. (NB the second test does not seem to be viable any more)

I think some other tests also succeed/fail randomly (after recording the server response so as to eliminate that variable), but I forgot to write those down. If I find some more time (coming Friday) I may add those and finish my work on the tests.

**Comment by towr** [comment]
I've made a pull request (#51) with some fix for the tests (but not necessarily fixes for what they test where the tests fail)

The following tests fail some of the time, and succeed some of the time:
* `nosetests tests.issues_test:TestIssues.test_issue109`
* `nosetests tests.issues_test:TestIssues.test_issue109bis`
* `nosetests tests.issues_test:TestIssues.test_issue35_wsdl`
* `nosetests tests.issues_test:TestIssues.test_issue44`
* `nosetests tests.sri_ec_test:TestSRI.test_validar`

(In addition, `nosetests tests.issues_test:TestIssues.test_issue123` fails consistently)

test_issue109, test_issue109bis, test_issue35_wsdl are all related to multiref processing, and they fail when the reference isn't resolved properly.

    Traceback (most recent call last):
      File "/home/towr/python/venv/lib/python3.4/site-packages/wrapt/wrappers.py", line 562, in __call__
        args, kwargs)
      File "/home/towr/python/venv/lib/python3.4/site-packages/vcr/cassette.py", line 65, in __call__
        return function(*args, **kwargs)
      File "/home/towr/python/pysimplesoap/tests/issues_test.py", line 436, in test_issue109
        self.assertIsInstance(ret['numberOfResults'], int)
    nose.proxy.TypeError: 'NoneType' object is not subscriptable

For test_issue44, the faultcode is sometimes mysteriously missing in action.

    Traceback (most recent call last):
      File "/home/towr/python/venv/lib/python3.4/site-packages/wrapt/wrappers.py", line 562, in __call__
        args, kwargs)
      File "/home/towr/python/venv/lib/python3.4/site-packages/vcr/cassette.py", line 65, in __call__
        return function(*args, **kwargs)
      File "/home/towr/python/pysimplesoap/tests/issues_test.py", line 154, in test_issue44
        self.assertEquals(e.faultcode, 's:InvalidUserNameOrPassword')
    nose.proxy.AttributeError: 'KeyError' object has no attribute 'faultcode'

And in `test_validar` the return value takes different shapes, sometimes it is just dicts within dicts within dicts, but other times there are lists involved.

    Traceback (most recent call last):
      File "/home/towr/python/venv/lib/python3.4/site-packages/wrapt/wrappers.py", line 562, in __call__
        args, kwargs)
      File "/home/towr/python/venv/lib/python3.4/site-packages/vcr/cassette.py", line 65, in __call__
        return function(*args, **kwargs)
      File "/home/towr/python/pysimplesoap/tests/sri_ec_test.py", line 40, in test_validar
        self.assertDictEqual(ret, {'RespuestaRecepcionComprobante': {'comprobantes': {'comprobante': {'mensajes': {'mensaje': {'informacionAdicional': 'Content is not allowed in prolog.', 'identificador': '35', 'tipo': 'ERROR', 'mensaje': 'ARCHIVO NO CUMPLE ESTRUCTURA XML'}}, 'claveAcceso': 'N/A'}}, 'estado': 'DEVUELTA'}})
    nose.proxy.AssertionError: {'Res[63 chars]es': [{'comprobante': {'claveAcceso': 'N/A', '[172 chars]}}]}} != {'Res[63 chars]es': {'comprobante': {'claveAcceso': 'N/A', 'm[170 chars]}}}}}
    Diff is 3649 characters long. Set self.maxDiff to None to see it.

**Comment by towr** [comment]
NB, you can set the hashseed for python with the environment variable PYTHONHASHSEED. Conveniently, all the ambiguous tests fail with `PYTHONHASHSEED=1`, and succeed with `PYTHONHASHSEED=2`

    PYTHONHASHSEED=1 nosetests tests.issues_test:TestIssues.test_issue109 # fails
    PYTHONHASHSEED=1 nosetests tests.issues_test:TestIssues.test_issue109bis # fails
    PYTHONHASHSEED=1 nosetests tests.issues_test:TestIssues.test_issue35_wsdl # fails
    PYTHONHASHSEED=1 nosetests tests.issues_test:TestIssues.test_issue44 # fails
    PYTHONHASHSEED=1 nosetests tests.sri_ec_test:TestSRI.test_validar # fails

    PYTHONHASHSEED=2 nosetests tests.issues_test:TestIssues.test_issue109 # succeeds
    PYTHONHASHSEED=2 nosetests tests.issues_test:TestIssues.test_issue109bis # succeeds
    PYTHONHASHSEED=2 nosetests tests.issues_test:TestIssues.test_issue35_wsdl # succeeds
    PYTHONHASHSEED=2 nosetests tests.issues_test:TestIssues.test_issue44 # succeeds
    PYTHONHASHSEED=2 nosetests tests.sri_ec_test:TestSRI.test_validar # succeeds

**Comment by reingart** [comment]
@towr : this is an interesting issue, do you have any clue on why it may be happening?
The library uses dicts structures a lot, maybe it is relaying (incorrectly) on the order of it elements.
It uses also dicts to store the elements structures, hashing them using tuples (including element name, namespace, etc. IIRC)
I don't use python3 a lot, but this seems to be related to it, right?

**Comment by reingart** [comment]
BTW, maybe PR #32 has something to do with this issue, I didn't have time to full review it...

**Comment by towr** [comment]
I don't think it has to do with python 3, since I get the same behavior with python 2.7 (though for some reason TestIssues.test_issue44 succeeds for seeds 1 and 2, but fails for 3, and TestSRI.test_validar vice versa, so the hashing is apparently slightly different in Py2 and Py3)

The only clue I have at the moment is that changing the hashseed has an effect. So as you already deduced it probably has something to do with dicts. 
I have some time today , so I'll see if I can find something.

PR #32 does seem to fix the issue for TestSRI.test_validar (after also changing the check in the test to the now consistent result), but it has no apparent effect for the other tests.

With regards to testing in general, I'm not really sure what a good approach would be to guard against non-deterministic behavior. You could run the tests a number of times with different seeds, but you can't test all possible seeds, so it's always a game of probabilities.

**Comment by towr** [comment]
With regard to the multiref tests, the problems seems to be that at the end of `client.py:wsdl_call_with_args`  the unmarshalling of the output returns a dict with two element in the case of a multiref, one of which is the result we want, and the other the multiref node. And then `wsdl_call_with_args` picks the first (bearing in mind they're ordered randomly).

I propose changing the last line of `wsdl_call_with_args` to
        responsetag = list(output.keys())[0]
        return resp and resp.get(responsetag, None)  # pass Response tag children
i.e. we explicitly take the value belonging to the responsetag specified for the output in the wsdl. 
(I'll add it to the pull-request)

That still leaves `TestIssues.test_issue44`

**Comment by towr** [comment]
hmm, that previous fix breaks `test_issue60`, but the webservice used there does not keep to its response specification. I suppose we could always fall back to returning the first element. ?

**Comment by towr** [comment]
I can't figure out where exactly `TestIssues.test_issue44` is going wrong. But it's already gone awry in `client.py:_xml_tree_to_services` when we get to `postprocess_element(elements, [])`.  Beyond that point, the value for  `('LoginFailure', 'element', 'http://clarizen.com/api/faults')` in `elements` is `{ }` in the failure case, whereas it should be `{'Message': <class 'str'>}`

Using a `SortedDict` instead of a `dict` for `elements` works, but I can't say whether that just hides underlying problems.
