### ISSUE TITLE
TypeError: Tag: IMKAD_Perceel invalid (type not found). Bug in pysimplesoap?

### ISSUE THREAD

**Issue by kramer65** [pysimplesoap/pysimplesoap#68]
I'm trying to use pysimplesoap to get information from a SOAP service from the Dutch land register ([full WSDL here](http://www1.kadaster.nl/1/schemas/kik-inzage/20141101/verzoekTotInformatie-2.1.wsdl)) with PySimpleSoap. Unfortunately it is a paid service, so it will be hard/impossible for anybody here to replicate. But maybe I can explain what the problem is. 

So far I managed to connect and request information about a specific property with the following code:

```
from pysimplesoap.client import SoapClient
client = SoapClient(wsdl='http://www1.kadaster.nl/1/schemas/kik-inzage/20141101/verzoekTotInformatie-2.1.wsdl', username='xxx', password='xxx', trace=True)

response = client.VerzoekTotInformatie(
    Aanvraag={
        'berichtversie': '4.7',  # Refers to the schema version: 
        'klantReferentie': klantReferentie,  # A reference we can set ourselves.
        'productAanduiding': '1185',  # a four-digit code referring to whether the response should be in "XML" (1185), "PDF" (1191) or "XML and PDF" (1057).
        'Ingang': {
            'Object': {
                'IMKAD_KadastraleAanduiding': {
                    'gemeente': 'ARNHEM AC',  # municipality
                    'sectie': 'AC',  # section code
                    'perceelnummer': '1234'  # Lot number
                }
            }
        }
    }
)
```

Because I set `trace=True` I get extensive log messages, and in those log messages I see a humongous xml output which includes all info which I request. BUT, I also get this traceback:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    'perceelnummer': perceelnummer
  File "/Library/Python/2.7/site-packages/pysimplesoap/client.py", line 181, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysimplesoap/client.py", line 346, in wsdl_call
    return self.wsdl_call_with_args(method, args, kwargs)
  File "/Library/Python/2.7/site-packages/pysimplesoap/client.py", line 372, in wsdl_call_with_args
    resp = response('Body', ns=soap_uri).children().unmarshall(output)
  File "/Library/Python/2.7/site-packages/pysimplesoap/simplexml.py", line 433, in unmarshall
    value = children and children.unmarshall(fn, strict)
  File "/Library/Python/2.7/site-packages/pysimplesoap/simplexml.py", line 433, in unmarshall
    value = children and children.unmarshall(fn, strict)
  File "/Library/Python/2.7/site-packages/pysimplesoap/simplexml.py", line 433, in unmarshall
    value = children and children.unmarshall(fn, strict)
  File "/Library/Python/2.7/site-packages/pysimplesoap/simplexml.py", line 380, in unmarshall
    raise TypeError("Tag: %s invalid (type not found)" % (name,))
TypeError: Tag: IMKAD_Perceel invalid (type not found)
```
as far as I understand, this means that the `IMKAD_Perceel` tag cannot be understood by the simplexml parser which I guess is because it could not read/find the definition of this tag in the wdsl file. 

I used [SoapUI](http://www.soapui.org/) to introspect the WSDL file, and I found an url to an .xsd-file in which I find a definition of the `IMKAD_Perceel`:
```
<xs:element name="IMKAD_Perceel" 
    substitutionGroup="ipkbo:IMKAD_OnroerendeZaak" 
    type="ipkbo:IMKAD_Perceel"
    />
```
The tag seams to be closing itself though. I guess this means the definition is empty. Am I correct in this? And if so, is this the reason that pysimplesoap thinks that `IMKAD_Perceel` is not defined? 

And most importantly: is this a bug in pysimplesoap, or is this something which I can somehow solve myself? All tips are welcome!

**Comment by kramer65** [comment]
I copied the xml from the command line, cleaned it a bit and created a pastebin out of it here: http://pastebin.com/eamQzGSt

Maybe that can help someone to understand why it goes wrong?

**Comment by matthewlenz** [comment]
Running in to this implementing a different service as well.  What is the work around for these issues?  Believe it has something to do with the substitutionGroup.  Please don't make me do this work in Java. :(

**Comment by kramer65** [comment]
@matthewlenz 
In the end I solved it by forking pysimplesoap and returning the raw xml instead of having pysimplesoap interpret the xml. I then converted it to a regular python dict using [xmltodict](https://github.com/martinblech/xmltodict) and started the tedious process of cleaning the (immensely nested and very dirty) data. Maybe this can help you as well?

If you're interested in my simple fork of pysimplesoap let me know. I can upload it to github for you if you want.

**Comment by matthewlenz** [comment]
Until I can find a soap lib that actually functions and is maintained I'll just use SoapUI to generate the queries, make them in to templates, send using a http client and parse the responses using xmltodict. :)

So basically what you are doing only I'll forgo using a lib at all if it can't serve it's purpose.

**Comment by dotnetdan** [comment]
@matthewlenz That sounds awful :(  I believe that pull request #42 may be able to solve your issue - if you have a chance to try it out please let me know.

**Comment by matthewlenz** [comment]
@dotnetdan the queries we are doing have very little/consistent input data and very little/consistent response data so it's not like I'm having to push/receive lots of crazy looking XML.  Have you tested your code with a schema that has substitutionGroups?  One of the main interfaces I have to use is loaded with them unfortunately.

**Comment by dotnetdan** [comment]
Ah, I wasn't even aware that xml schema's had substitionGroups.  PySimpleSoap's wsdl parser doesn't have logic for specifically handling that.  I believe that ultimately a discussion may be needed to consider using a complete XML parser instead custom logic.

**Comment by matthewlenz** [comment]
I wouldn't be surprised if you found that a large portion of all the 'type not found' errors people get with pysimplesoap are due to substitutionGroups.  kramer65 had posted on http://stackoverflow.com/questions/30258321/typeerror-in-soap-request-using-pysimplesoap and someone identified the issue and came up with a possible solution using unmarshall.  Is there a way to print out all of the type data that has been parsed by PSS?

**Comment by dotnetdan** [comment]
Yes, once you instantiate a SoapClient, you can ```print client.services```

**Comment by AW8000** [comment]
@kramer65 Hi, did you manage to get the SOAP connection working with the KIK-inzage and if so, does it still work with the latest version of SOAP/KIK? I'm trying to make a connection myself as well, but the documentation of the Kadaster is so poor.. I also tried to google solutions but apparently your 5 year old post is the only thing I found...
