### ISSUE TITLE
iteritems error in python 3.5

### ISSUE THREAD

**Issue by shipperizer** [pysimplesoap/pysimplesoap#97]
Leftovers of old syntax: 
```bash
Installing collected packages: pysimplesoap
  Running setup.py install for pysimplesoap
Successfully installed pysimplesoap-1.16
(env) [shipperizer@archer portal]$ python
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysimplesoap
>>> from pysimplesoap.client import SoapClient
>>> client = SoapClient(wsdl="http://localhost:8080/services/AdministrationService?wsdl", trace=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shipperizer/development/portal/env/lib/python3.5/site-packages/pysimplesoap/client.py", line 173, in __init__
    self.services = wsdl and self.wsdl_parse(wsdl, cache=cache)
  File "/home/shipperizer/development/portal/env/lib/python3.5/site-packages/pysimplesoap/client.py", line 836, in wsdl_parse
    services = self._xml_tree_to_services(wsdl, cache, force_download)
  File "/home/shipperizer/development/portal/env/lib/python3.5/site-packages/pysimplesoap/client.py", line 757, in _xml_tree_to_services
    for name, msg in op['fault_msgs'].iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by Niades** [comment]
It is fixed on the master branch, but PyPI contains older version :disappointed:

**Comment by Niades** [comment]
I have just discovered that you can install packages directly from github with pip:
```
pip install -e git+git@github.com:pysimplesoap/pysimplesoap.git@7078d1a34554719fd8fb432a9e79ce356c0e751d#egg=PySimpleSOAP-master
```
You can change the commit hash to a branch name or a tag name. For more info on using `pip` with CVS see [this link](http://pip.readthedocs.org/en/stable/reference/pip_install/#vcs-support).

**Comment by shipperizer** [comment]
Thanks dude, i can confirm it's working fine now
